name: CI

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node_version: 14.x
          
      - name: Instal Dependencies
        run: yarn
      
      - name: Build
        run: yarn build
      
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "~/app/Ignite/NodeJs/RENTALX"
          
      - name: update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script : |
            vf ~/app/api-rentex
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart rentx_api
            ls -al
